# Generated by Django 5.0.6 on 2024-06-21 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('html_creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlcreatormodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='htmlcreatormodel',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
